# Generated by Django 3.2.8 on 2021-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='notes',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='identity',
            name='number',
            field=models.IntegerField(max_length=20),
        ),
    ]
