# Generated by Django 3.2.8 on 2021-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_me', '0002_auto_20211205_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='number',
            field=models.IntegerField(default=-2678),
        ),
    ]
