# Generated by Django 3.2.8 on 2021-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_me', '0003_alter_identity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='number',
            field=models.IntegerField(default='1234-456-3456'),
        ),
    ]
